// flow-typed signature: 9272b2eed9fdd5e5474856122d89ec2c
// flow-typed version: <<STUB>>/isomorphic-unfetch_v2/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-unfetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-unfetch' {
  declare module.exports: (
    url: string,
    options?: {
      method?: string,
      headers?: Object,
      credentials?: 'include',
      body?:
        | void
        | null
        | string
        | URLSearchParams
        | FormData
        | Blob
        | ArrayBuffer
        | $ArrayBufferView,
    },
    // TODO: This is really a "Response-like". Type this properly eventually. See https://github.com/developit/unfetch#response-methods-and-attributes
  ) => Promise<Response>;
}
