// @flow
/**
 * Part of GDL gdl-frontend.
 * Copyright (C) 2018 GDL
 *
 * See LICENSE
 */

/**
 * Creates an object with the same keys as object and values generated by calling the provided function for each key value of the object
 */
export default function mapValues(
  obj: {},
  callback: (currentValue: any, key: string, obj: {}) => any
) {
  return Object.entries(obj).reduce((acc, [key, value]) => {
    const newValue = callback(value, key, obj);
    acc[key] = newValue;
    return acc;
  }, {});
}
